/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jni_Host */

#ifndef _Included_com_example_jni_Host
#define _Included_com_example_jni_Host
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jni_Host
 * Method:    sendRunnable
 * Signature: (Ljava/lang/Runnable;)V
 */
JNIEXPORT void JNICALL Java_com_example_jni_Host_sendRunnable
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
