/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jni_MainApp */

#ifndef _Included_com_example_jni_MainApp
#define _Included_com_example_jni_MainApp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jni_MainApp
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_jni_MainApp_sayHello
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
